"""esquema inicial: usuario, orientacao, marco, documento, versao_documento, ata, parecer, log_auditoria

Revision ID: 092f0d191451
Revises: 
Create Date: 2026-07-19 16:30:33.089195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092f0d191451'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.Enum('admin', 'orientador', 'orientando', name='papel_usuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)

    op.create_table('log_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('entidade', sa.String(length=50), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('dados_json', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_auditoria_timestamp'), ['timestamp'], unique=False)

    op.create_table('orientacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orientador_id', sa.Integer(), nullable=False),
    sa.Column('orientando_id', sa.Integer(), nullable=False),
    sa.Column('modalidade', sa.Enum('ic', 'mestrado', 'doutorado', name='modalidade_orientacao'), nullable=False),
    sa.Column('titulo_projeto', sa.String(length=255), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim_prevista', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ativa', 'concluida', 'suspensa', 'cancelada', name='status_orientacao'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['orientador_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['orientando_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orientacao_id', sa.Integer(), nullable=False),
    sa.Column('data_reuniao', sa.Date(), nullable=False),
    sa.Column('pauta', sa.Text(), nullable=False),
    sa.Column('deliberacoes', sa.Text(), nullable=False),
    sa.Column('redigida_por', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('rascunho', 'finalizada', name='status_ata'), nullable=False),
    sa.Column('finalizada_em', sa.DateTime(), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['orientacao_id'], ['orientacao.id'], ),
    sa.ForeignKeyConstraint(['redigida_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orientacao_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_prevista', sa.Date(), nullable=False),
    sa.Column('data_conclusao', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'em_andamento', 'concluido', name='status_marco'), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('conclusao_sinalizada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['orientacao_id'], ['orientacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orientacao_id', sa.Integer(), nullable=False),
    sa.Column('marco_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['marco_id'], ['marco.id'], ),
    sa.ForeignKeyConstraint(['orientacao_id'], ['orientacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versao_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('numero_versao', sa.Integer(), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('nome_fisico', sa.String(length=64), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=False),
    sa.Column('mimetype', sa.String(length=100), nullable=False),
    sa.Column('enviado_por', sa.Integer(), nullable=False),
    sa.Column('enviado_em', sa.DateTime(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ),
    sa.ForeignKeyConstraint(['enviado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento_id', 'numero_versao', name='uq_documento_versao'),
    sa.UniqueConstraint('nome_fisico')
    )
    op.create_table('parecer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orientacao_id', sa.Integer(), nullable=False),
    sa.Column('versao_documento_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('andamento', 'documento', 'marco', name='tipo_parecer'), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('resultado', sa.Enum('aprovado', 'aprovado_com_ressalvas', 'reprovado', name='resultado_parecer'), nullable=False),
    sa.Column('emitido_por', sa.Integer(), nullable=False),
    sa.Column('emitido_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['emitido_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['orientacao_id'], ['orientacao.id'], ),
    sa.ForeignKeyConstraint(['versao_documento_id'], ['versao_documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parecer')
    op.drop_table('versao_documento')
    op.drop_table('documento')
    op.drop_table('marco')
    op.drop_table('ata')
    op.drop_table('orientacao')
    with op.batch_alter_table('log_auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_auditoria_timestamp'))

    op.drop_table('log_auditoria')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    # ### end Alembic commands ###
