"""Instante da ultima tentativa de aviso

Revision ID: 50fdafd127f9
Revises: b18734f0656f
Create Date: 2026-07-21 13:39:02.601775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50fdafd127f9'
down_revision = 'b18734f0656f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avisos_tentados_em', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_email', schema=None) as batch_op:
        batch_op.drop_column('avisos_tentados_em')

    # ### end Alembic commands ###
