"""Registro de quem ja recebeu aviso no dia

Revision ID: 5e3dd48b9720
Revises: 07c3c4662e8d
Create Date: 2026-07-21 15:20:10.938833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3dd48b9720'
down_revision = '07c3c4662e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avisos_entregues', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_email', schema=None) as batch_op:
        batch_op.drop_column('avisos_entregues')

    # ### end Alembic commands ###
