"""Configuração de envio de e-mail, editável pelo administrador

Linha única (id=1), criada sob demanda por `ConfiguracaoEmail.vigente()`. A
senha de app do SMTP é guardada cifrada (`services/cripto.py`), e a tabela fica
deliberadamente fora do pacote de backup — ver o comentário em
`services/backup.py`.

O `downgrade` perde a configuração, que precisa ser reinformada. Não há como
evitar: o dado só existe nesta tabela.

Revision ID: a868daac099a
Revises: d7b3f915a6c8
Create Date: 2026-07-21
"""
from alembic import op
import sqlalchemy as sa


revision = 'a868daac099a'
down_revision = 'd7b3f915a6c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('servidor', sa.String(length=255), nullable=False),
    sa.Column('porta', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=254), nullable=False),
    sa.Column('senha_cifrada', sa.Text(), nullable=True),
    sa.Column('remetente_nome', sa.String(length=120), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atualizado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracao_email')
    # ### end Alembic commands ###
