"""Marcador do disparo diario de avisos

Revision ID: b18734f0656f
Revises: a868daac099a
Create Date: 2026-07-21 13:24:37.967592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18734f0656f'
down_revision = 'a868daac099a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avisos_enviados_em', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_email', schema=None) as batch_op:
        batch_op.drop_column('avisos_enviados_em')

    # ### end Alembic commands ###
