"""Ligacao ata-marco: marcos discutidos na reuniao

Revision ID: b25557e3b3d2
Revises: 5e3dd48b9720
Create Date: 2026-07-21 20:26:07.396444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25557e3b3d2'
down_revision = '5e3dd48b9720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ata_marco',
    sa.Column('ata_id', sa.Integer(), nullable=False),
    sa.Column('marco_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ata_id'], ['ata.id'], ),
    sa.ForeignKeyConstraint(['marco_id'], ['marco.id'], ),
    sa.PrimaryKeyConstraint('ata_id', 'marco_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ata_marco')
    # ### end Alembic commands ###
